spring:
  profile:
    active:
     - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-jason-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-jason-test

  